export const IMAGES = {
    BITCOIN: require('../../assets/images/bitcoin.png'),
    CHAT_ICON: require('../../assets/images/chatIcon.png'),
    FB_ICON: require('../../assets/images/fbIcon.png'),
    GOOGLE_ICON: require('../../assets/images/googleIcon.png'),
    HAND_ICON: require('../../assets/images/handIcon.png'),
    HEADER_LOGO: require('../../assets/images/Header.png'),
    HOME_ICON: require('../../assets/images/homeIcon.png'),
    INSTA_ICON: require('../../assets/images/instaIcon.png'),
    LOGIN_BG_IMAGE: require('../../assets/images/loginImage.png'),
    APPLOGO: require('../../assets/images/Loopin_logo.png'),
    MSG_ICON: require('../../assets/images/msgIcon.png'),
    PENCIL_ICON: require('../../assets/images/pencilIcon.png'),
    RATING_ICON: require('../../assets/images/ratingIcon.png'),
    TWITTER_ICON: require('../../assets/images/twiterIcon.png'),
    ONBOARDING_LOGO: require('../../assets/images/onBoardingLogo.png'),
    BUNGEE: require('../../assets/images/bungee.png'),
    ETHERIUM: require('../../assets/images/etherium.png'),
    PROVY: require('../../assets/images/provy.png'),
    HEART_ICON: require('../../assets/images/heart.png'),
    KEY_ICON: require('../../assets/images/key.png'),
    CHAT_CONTAINER: require('../../assets/images/chat_container.png'),
    NEWS_PERSON: require('../../assets/images/newsperson.png'),
    THUMBS_UP_BLACK: require('../../assets/images/thumbsupblack.png'),
    THUMBS_UP_GREY: require('../../assets/images/thumbsupgrey.png'),
    EYE_ICON: require('../../assets/images/eyemouth.png'),
    FILL_HEART_ICON: require('../../assets/images/fillheart.png'),
    CUBE_LOGO: require('../../assets/images/Loopin_logo.png'),
    RATING_0: require('../../assets/images/0.png'),
    RATING_25: require('../../assets/images/25.png'),
    RATING_50: require('../../assets/images/50.png'),
    RATING_75: require('../../assets/images/75.png'),
    RATING_100: require('../../assets/images/100.png'),
    DOLLOR: require('../../assets/images/dollar.png'),
    
    // New images
    ADAPTIVE_ICON: require('../../assets/images/adaptive-icon.png'),
    ARROWS_DOWN_UP: require('../../assets/images/arrows-down-up.png'),
    DOWN_ARROW: require('../../assets/images/downnArrow.png'),
    FAVICON: require('../../assets/images/favicon.png'),
    ICON: require('../../assets/images/icon.png'),
    MUSIC_ICON: require('../../assets/images/musicIcon.png'),
    PARTIAL_REACT_LOGO: require('../../assets/images/partial-react-logo.png'),
    REACT_LOGO: require('../../assets/images/react-logo.png'),
    SPLASH_ICON: require('../../assets/images/splash-icon.png'),
    
    // Binance images
    BINANCE_ABOUT_NETWORK_FEE: require('../../assets/images/binance/aboutnetworkfee.png'),
    BINANCE_LOGO: require('../../assets/images/binance/binanncelogo.png'),
    BINANCE_DEPOSIT: require('../../assets/images/binance/deposit.png'),
    BINANCE_ESTIMATED_BALANCE: require('../../assets/images/binance/estimatedbalance.png'),
    BINANCE_ICON: require('../../assets/images/binance/Icon.png'),
    BINANCE_LOGIN: require('../../assets/images/binance/login.png'),
    BINANCE_MONEYBOX: require('../../assets/images/binance/moneybox.png'),
    BINANCE_RECENT_WITHDRAW: require('../../assets/images/binance/recentWithdraw.png'),
    BINANCE_SELECT_COIN: require('../../assets/images/binance/selectcoin.png'),
    BINANCE_SELECT_COIN_ERROR: require('../../assets/images/binance/selectcoinerror.png'),
    BINANCE_WITHDRAW_TO: require('../../assets/images/binance/withdrawto.png'),
    BINANCE_WITHDRAW_TO_ERROR: require('../../assets/images/binance/withdrawtoerror.png'),
    
    // Binance white images
    BINANCE_WHITE_CONFIRM_ORDER: require('../../assets/images/binance/white/cofirmorder.png'),
    BINANCE_WHITE_LOGIN: require('../../assets/images/binance/white/login.png'),
    BINANCE_WHITE_SEND_USDT: require('../../assets/images/binance/white/sendUsdt.png'),
    BINANCE_WHITE_USDT: require('../../assets/images/binance/white/usdt.png'),
    BINANCE_WHITE_WITHDRAW: require('../../assets/images/binance/white/withdraw.png'),
    OKX_LOGO: require('../../assets/images/binance/white/ohxlogo.png'),
    BINANCE_WHITE_BOTTOM_SHEET: require('../../assets/images/binance/white/bottomsheet.png'),
    
    // Bybit images
    BYBIT_BASE_ASSETS: require('../../assets/images/bybit/baseAssets.png'),
    BYBIT_BOTTOM_SHEET: require('../../assets/images/bybit/bottomSheet.png'),
    BYBIT_CHOOSE_RECEIPT: require('../../assets/images/bybit/chooseReceipt.png'),
    BYBIT_CONNECT_MY_COINBASE: require('../../assets/images/bybit/connectmycoinbase.png'),
    BYBIT_CRYPTO: require('../../assets/images/bybit/crypto.png'),
    BYBIT_SEND_CONFIRM: require('../../assets/images/bybit/sendConfirm.png'),
    BYBIT_SEND_CONTACT: require('../../assets/images/bybit/sendContact.png'),
    BYBIT_SEND_SUCCESS: require('../../assets/images/bybit/sendSuccess.png'),
    BYBIT_ZERO_GBP: require('../../assets/images/bybit/zeroGBP.png'),
    BYBIT_LOGO: require('../../assets/images/bybit/bybit-logo.png'),
    
    // Coinbase images
    COINBASE_ACCOUNT: require('../../assets/images/coinbase/account.png'),
    COINBASE_LOGO: require('../../assets/images/coinbase/coinbase.png'),
    COINBASE_SELECT: require('../../assets/images/coinbase/selectCoinnbase.png'),
    COINBASE_ETH_ADDRESS: require('../../assets/images/coinbase/ethAddress.png'),
    COINBASE_HUNDRED_ETH: require('../../assets/images/coinbase/hundredEth.png'),
    COINBASE_LOGIN: require('../../assets/images/coinbase/login.png'),
    COINBASE_SEND_99: require('../../assets/images/coinbase/send99.png'),
    COINBASE_SEND_CRYPTO: require('../../assets/images/coinbase/sendcrypto.png'),
    COINBASE_SEND_ETH: require('../../assets/images/coinbase/sendeth.png'),
    COINBASE_TRADE: require('../../assets/images/coinbase/trade.png'),
    COINBASE_ZERO_USD: require('../../assets/images/coinbase/zerousd.png'),
}